name: Enforce HandsOn Folder Ownership

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-folder-ownership:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set PR environment variables
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_USER=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Skip excluded users
        run: |
          EXCLUDED=("dgarijo" "ocorcho" "rgcmme")
          for u in "${EXCLUDED[@]}"; do
            if [ "$PR_USER" = "$u" ]; then
              echo "PR user $u is excluded from checks."
              exit 0
            fi
          done

      - name: Find added or deleted files
        id: files
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          git fetch origin $BASE --depth=1
          CHANGED_FILES=$(git diff --name-only --diff-filter=AD origin/$BASE)
          echo "$CHANGED_FILES"
          # Save as multi-line output
          {
            echo "files<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Verify changes are in user's group folder
        run: |
          INVALID_CHANGES=()

          for f in ${{ steps.files.outputs.files }}; do
            # Only check files under HandsOn/GroupXX/
            if [[ "$f" =~ ^HandsOn/Group[0-9]{2}/ ]]; then
              # Extract root group directory
              ROOT_DIR=$(echo "$f" | cut -d'/' -f1-2)
              README="$ROOT_DIR/README.md"

              if [ -f "$README" ]; then
                if ! grep -q "$PR_USER" "$README"; then
                  INVALID_CHANGES+=("$f")
                fi
              else
                # Missing README.md
                INVALID_CHANGES+=("$f")
              fi
            fi
            # Files outside HandsOn/GroupXX/ are ignored
          done

          if [ ${#INVALID_CHANGES[@]} -gt 0 ]; then
            echo "Unauthorized file changes detected in:"
            for f in "${INVALID_CHANGES[@]}"; do
              echo " - $f"
            done
            exit 1
          else
            echo "All changes are within user's group folder."
          fi
