name: Check Homework Report

on:
  workflow_dispatch:

jobs:
  verify-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rdflib

      - name: Find and run Python scripts from PR
        id: run_script
        run: |
          PR=${{ github.event.pull_request.number }}
          BASE=${{ github.event.pull_request.base.ref }}

          # Fetch the merge commit for the PR
          git fetch origin pull/$PR/merge:pr-merge
          git fetch origin $BASE --depth=1

          # List only newly added Python files compared to base
          FILES=$(git diff --name-only --diff-filter=A origin/$BASE..pr-merge | grep '\.py$' || true)

          echo "New Python files containing 'task':"
          echo "$FILES"

          # Save the list of files as an output
          {
            echo "files<<EOF"
            echo "$FILES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          if [ -z "$FILES" ]; then
            echo "No new Python files with 'task' in the name found."
          fi

          # Run each new Python file that contains 'task' in its name
          for f in $FILES; do
            if echo "$f" | grep -Eiq "task"; then
              echo "Running script $f..."
              python "$f" || {
                echo "Script $f failed to run."
                exit 1
              }
            else
              echo "Skipping $f (not a task file)."
            fi
          done

      - name: Check for generated report files (optional)
        run: |
          echo "Checking for any generated report files..."
          ls report_result_*.txt 2>/dev/null || echo "No report files generated."

      - name: Upload reports as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-reports
          path: |
            report_result_*.txt
          if-no-files-found: ignore
